name: Build and Test

on:
  workflow_call: # <-- makes it callable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BUILD
        run: echo "build"
      
      - name: TEST
        run: echo "test"
        
