# .github/workflows/build-test.yml
name: Build And Test Workflow

on:
  workflow_call:  # Allows this workflow to be called by other workflows
  workflow_dispatch:  # Allows manual triggering
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: First Bash Step
        run: echo "First step executed"
          
      - name: Second Bash Step
        run: echo "Second step executed"
