# .github/workflows/deploy.yml
name: Deploy

on:
  workflow_call: # <-- also makes it callable

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY ASSET
        run: echo "deploy asset"
      
      - name: DEPLOY JAR
        run: echo "deploy jar"
