name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    name: deploy release
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy DEV Step
        if:  ${{ inputs.environment == 'dev' }}
        run: echo "Deploying to environment ${{ inputs.environment }}"
      - name: Deploy STAGING Step
        if:  ${{ inputs.environment == 'staging' }}
        run: echo "Deploying to environment ${{ inputs.environment }}"
      - name: Deploy PROD Step
        if:  ${{ inputs.environment == 'prod'}}
        run: echo "Deploying to environment ${{ inputs.environment }}"