# .github/workflows/orchestrator.yml
name: Orchestrator Workflow

on:
  push:
    branches: 
      - main
      - feature/**
      - qa
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log orchestrator start
        run: |
          echo "🎯 Orchestrator workflow started"
          echo "Triggering build workflow..."
          
  call-build:
    needs: orchestrate
    uses: ./.github/workflows/build-test.yml

