name: Orchestrator Pipeline

on:
  push:
    branches:
      - main
      - qa/*
      - feature/*

jobs:
  set-env:
    name: set: environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - id: setenv
        run: |
          case "${GITHUB_REF#refs/heads/}" in
            feature/*) echo "environment=dev" >> "$GITHUB_OUTPUT" ;;
            qa/*) echo "environment=staging" >> "$GITHUB_OUTPUT" ;;
            main) echo "environment=prod" >> "$GITHUB_OUTPUT" ;;
            *) echo "environment=unknown" >> "$GITHUB_OUTPUT" ;;
          esac

  build-test:
    name: build: test
    needs: set-env
    uses: ./.github/workflows/build-test.yml
    with:
      environment: ${{ needs.set-env.outputs.environment }}

  deploy:
    name: deploy: release
    needs: build-test
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ needs.set-env.outputs.environment }}

