# .github/workflows/orchestrator.yml
name: Orchestrator Workflow

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'BRanch name to resolve environment'
        required: true
        type: string
  workflow_dispatch:  # Allows manual triggering

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Set Environment Based on Branch
        id: set-env
        run: |
          BRANCH_NAME="${{ inputs.branch_name }}"
          echo "Branch name: $BRANCH_NAME"
          
          if [[ $BRANCH_NAME == feature* ]]; then
            ENVIRONMENT="dev"
          elif [[ $BRANCH_NAME == qa* ]]; then
            ENVIRONMENT="staging"
          elif [[ $BRANCH_NAME == "main" ]]; then
            ENVIRONMENT="prod"
          else
            ENVIRONMENT="dev"  # default fallback
          fi
          
          echo "Resolved environment: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Log orchestrator start
        run: |
          echo "🎯 Orchestrator workflow started"
          echo "Triggering build workflow..."
          
  call-build:
    needs: orchestrate
    uses: ./.github/workflows/build-test.yml
    with:
      environment: ${{ needs.orchestrate.outputs.environment }}
  
  call-deploy:
    needs: [orchestrate, call-build]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ needs.orchestrate.outputs.environment }}

